//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientComplentTrackerEntities1 : DbContext
    {
        public ClientComplentTrackerEntities1()
            : base("name=ClientComplentTrackerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Client_Login_Page> Client_Login_Page { get; set; }
        public DbSet<module> modules { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<Severity> Severities { get; set; }
        public DbSet<Typ> Typs { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<TestEnvironment> TestEnvironments { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<Map_ClientName> Map_ClientName { get; set; }
        public DbSet<Map_Version_client> Map_Version_client { get; set; }
        public DbSet<Map_Version_Product> Map_Version_Product { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ActionStatus> ActionStatus { get; set; }
    }
}
