//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCTAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typ
    {
        public int TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
